// Generated by LiveScript 1.2.0
(function(){
  var Test;
  this.Level.Test = Test = (function(superclass){
    var prototype = extend$((import$(Test, superclass).displayName = 'Test', Test), superclass).prototype, constructor = Test;
    prototype.init = function(level){
      var x$, y$, z$;
      x$ = level;
      y$ = x$.platform;
      y$.black(0, 200, 800, 300, this.upper);
      y$.white(50, 150, 500, 200, this.lower);
      z$ = x$.player;
      z$.black(200, 100);
      z$.white(600, 220);
      x$.gray(0, 0, 50, 50, Level.Test);
      return x$;
    };
    prototype.upper = function(platform){
      platform.inside.z = 10;
      return platform.customUpdate = null;
    };
    prototype.lower = function(platform){
      platform.inside.z = 5;
      return platform.customUpdate = null;
    };
    function Test(){
      Test.superclass.apply(this, arguments);
    }
    return Test;
  }(Level));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
