// Generated by LiveScript 1.2.0
(function(){
  var Three;
  this.Level.Three = Three = (function(superclass){
    var prototype = extend$((import$(Three, superclass).displayName = 'Three', Three), superclass).prototype, constructor = Three;
    prototype.levelWidth = 1500;
    prototype.levelHeight = 1500;
    prototype.init = function(level){
      var x$, y$, z$;
      x$ = level;
      y$ = x$.platform;
      y$.black(0, 285, 861, 78);
      y$.black(0, 0, 291, 1500);
      y$.black(507, 159, 100, 403, this.canMove);
      y$.black(951, 283, 259, 197);
      y$.black(1127, 480, 84, 349);
      y$.black(625, 915, 875, 91);
      y$.black(1086, 725, 414, 94, this.canMove);
      y$.black(1301, 499, 199, 82);
      x$.text(1248, 587, "'R'\nto retry");
      x$.danger(793, 432, 195, 48);
      x$.danger(0, 1419, 1500, 81);
      z$ = x$.player;
      z$.black(376, 199);
      z$.white(534, 461);
      x$.gray(664, 910, 185, 185, Level.One);
      return x$;
    };
    prototype.canMove = function(platform){
      platform.inside.body.immovable = false;
      return platform.customUpdate = null;
    };
    function Three(){
      Three.superclass.apply(this, arguments);
    }
    return Three;
  }(Level));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
