// Generated by LiveScript 1.2.0
(function(){
  var Three;
  this.Level.Three = Three = (function(superclass){
    var prototype = extend$((import$(Three, superclass).displayName = 'Three', Three), superclass).prototype, constructor = Three;
    prototype.levelWidth = 1500;
    prototype.levelHeight = 1500;
    prototype.init = function(level){
      var x$, y$, z$;
      x$ = level;
      y$ = x$.platform;
      y$.black(0, 285, 861, 78);
      y$.black(0, 0, 291, 289);
      y$.black(507, 159, 100, 403, this.movesOnAxis('x'));
      y$.black(951, 283, 259, 197);
      y$.black(1127, 480, 84, 349);
      y$.black(625, 915, 875, 91);
      y$.black(1086, 725, 414, 94, this.movesOnAxis('y'));
      x$.danger(793, 432, 195, 48);
      x$.danger(0, 1419, 1500, 81);
      z$ = x$.player;
      z$.black(376, 199);
      z$.white(534, 461);
      x$.gray(664, 910, Level.One);
      return x$;
    };
    prototype.movesOnAxis = curry$((function(axis, platform){
      var otherAxis, x$;
      otherAxis = (function(){
        switch (axis) {
        case 'y':
          return 'x';
        case 'x':
          return 'y';
        }
      }());
      x$ = platform.inside.body;
      x$.immovable = false;
      x$.maxVelocity[otherAxis] = 0;
      x$.maxVelocity[axis] = 150;
      return platform.customUpdate = null;
    }), true);
    function Three(){
      this.movesOnAxis = bind$(this, 'movesOnAxis', prototype);
      Three.superclass.apply(this, arguments);
    }
    return Three;
  }(Level));
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
