// Generated by LiveScript 1.2.0
(function(){
  var Two;
  this.Level.Two = Two = (function(superclass){
    var prototype = extend$((import$(Two, superclass).displayName = 'Two', Two), superclass).prototype, constructor = Two;
    prototype.levelWidth = 2000;
    prototype.levelHeight = 2000;
    prototype.init = function(level){
      var x$, y$, z$;
      x$ = level;
      y$ = x$.platform;
      y$.black(0, 367, 745, 986);
      y$.black(0, 0, 67, 368);
      y$.black(66, 0, 1164, 121);
      y$.white(183, 976, 297, 222);
      y$.white(314, 359, 125, 623);
      z$ = x$.player;
      z$.black(150, 200);
      z$.white(170, 1200);
      x$.gray(1500, 700);
      x$.nextLevel(Level.One);
      return x$;
    };
    function Two(){
      Two.superclass.apply(this, arguments);
    }
    return Two;
  }(Level));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
