// Generated by LiveScript 1.2.0
(function(){
  var Two;
  this.Level.Two = Two = (function(superclass){
    var prototype = extend$((import$(Two, superclass).displayName = 'Two', Two), superclass).prototype, constructor = Two;
    prototype.levelWidth = 2000;
    prototype.levelHeight = 2000;
    prototype.init = function(level){
      var x$, y$, z$;
      x$ = level;
      y$ = x$.platform;
      y$.black(0, 367, 745, 986);
      y$.black(474, 119, 163, 251);
      y$.black(66, 0, 1164, 121);
      y$.black(1267, 364, 445, 159);
      y$.black(1227, 0, 707, 184);
      y$.black(1824, 182, 110, 704);
      y$.black(1562, 784, 271, 144);
      y$.white(183, 976, 297, 222);
      y$.white(478, 976, 268, 73);
      y$.white(564, 684, 61, 181);
      y$.white(0, 527, 746, 55);
      y$.white(375, 363, 99, 116);
      y$.black(744, 644, 328, 231, this.elevator);
      x$.danger(0, 1919, 2000, 81);
      z$ = x$.player;
      z$.black(684, 261);
      z$.white(170, 1200);
      x$.gray(1522, 783, Level.Three);
      return x$;
    };
    prototype.elevator = function(platform){
      var body;
      body = platform.body;
      if (body.y <= 107) {
        return body.velocity.y = 150;
      } else if (body.y >= 644) {
        return body.velocity.y = -150;
      }
    };
    function Two(){
      this.elevator = bind$(this, 'elevator', prototype);
      Two.superclass.apply(this, arguments);
    }
    return Two;
  }(Level));
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
